name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Ruff linter
        uses: astral-sh/ruff-action@v1
        with:
          args: "check ."

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB_AUTH=${{ secrets.POSTGRES_DB_AUTH }}" >> .env
          echo "POSTGRES_DB_UNIVERSITY=${{ secrets.POSTGRES_DB_UNIVERSITY }}" >> .env
          echo "UNIVERSITY_SERVICE_INTERNAL_URL=${{ secrets.UNIVERSITY_SERVICE_INTERNAL_URL }}" >> .env
          echo "UNIVERSITY_SERVICE_API_URL=${{ secrets.UNIVERSITY_SERVICE_API_URL }}" >> .env
          echo "AUTH_SERVICE_INTERNAL_URL=${{ secrets.AUTH_SERVICE_INTERNAL_URL }}" >> .env
          echo "AUTH_SERVICE_API_URL=${{ secrets.AUTH_SERVICE_API_URL }}" >> .env

      - name: Build tests image
        run: |
          docker build -t my-tests .

      - name: Start test system
        run: |
          docker compose up -d

      - name: Run tests
        run: |
          docker run \
            --network backend-tests_default \
            -v $(pwd)/allure-results:/app/allure-results \
            -v $(pwd)/allure-report:/app/allure-report \
            --env-file .env \
            my-tests

      - name: Generate Allure report
        if: always()
        run: |
          docker run --rm \
            -v $(pwd)/allure-results:/app/allure-results \
            -v $(pwd)/allure-report:/app/allure-report \
            my-tests \
            sh -c "allure generate /app/allure-results -o /app/allure-report --clean"

      - name: Stop containers
        if: always()
        run: |
          docker compose down -v

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: always()
    steps:
      - name: Download Allure report
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: allure-report/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: allure-report
          publish_branch: gh-pages